#                     . .:.:.:.:. .:\     /:. .:.:.:.:. ,
#                .-._  `..:.:. . .:.:`- -':.:. . .:.:.,'  _.-.
#               .:.:.`-._`-._..-''_...---..._``-.._.-'_.-'.:.:.
#            .:.:. . .:_.`' _..-''._________,``-.._ `.._:. . .:.:.
#         .:.:. . . ,-'_.-''      ||_-(O)-_||      ``-._`-. . . .:.:.
#        .:. . . .,'_.'           '---------'           `._`.. . . .:.
#      :.:. . . ,','               _________               `.`. . . .:.:
#     `.:.:. .,','            _.-''_________``-._            `._.     _.'
#   -._  `._./ /            ,'_.-'' ,       ``-._`.          ,' '`:..'  _.-
#  .:.:`-.._' /           ,','                   `.`.       /'  '  \\.-':.:.
#  :.:. . ./ /          ,','               ,       `.`.    / '  '  '\\. .:.:
# :.:. . ./ /          / /    ,                      \ \  :  '  '  ' \\. .:.:
# .:. . ./ /          / /            ,          ,     \ \ :  '  '  ' '::. .:.
# :. . .: :    o     / /                               \ ;'  '  '  ' ':: . .:
# .:. . | |   /_\   : :     ,                      ,    : '  '  '  ' ' :: .:.
# :. . .| |  ((<))  | |,          ,       ,             |\'__',-._.' ' ||. .:
# .:.:. | |   `-'   | |---....____                      | ,---\/--/  ' ||:.:.
# ------| |         : :    ,.     ```--..._   ,         |''  '  '  ' ' ||----
# _...--. |  ,       \ \             ,.    `-._     ,  /: '  '  '  ' ' ;;..._
# :.:. .| | -O-       \ \    ,.                `._    / /:'  '  '  ' ':: .:.:
# .:. . | |_(`__       \ \                        `. / / :'  '  '  ' ';;. .:.
# :. . .<' (_)  `>      `.`.          ,.    ,.     ,','   \  '  '  ' ;;. . .:
# .:. . |):-.--'(         `.`-._  ,.           _,-','      \ '  '  '//| . .:.
# :. . .;)()(__)(___________`-._`-.._______..-'_.-'_________\'  '  //_:. . .:
# .:.:,' \/\/--\/--------------------------------------------`._',;'`. `.:.:.
# :.,' ,' ,'  ,'  /   /   /   ,-------------------.   \   \   \  `. `.`. `..:
# ,' ,'  '   /   /   /   /   //                   \\   \   \   \   \  ` `.SSt
---
comment:
  header: Hi ğŸ‘‹ğŸ¾, there you earthlings ğŸ‘©ğŸ½â€ğŸŒ¾ ğŸ‘¨ğŸ¿â€ğŸŒ¾ ğŸ„ ğŸ– ğŸ¦ƒ
  footer: "Be kind to animals ğŸ„ ğŸ– ğŸ¦ƒ"

labels:
  - name: mvpr ğŸŒ®
    labeled:
      pr:
        body: |
          ğŸ· ( MVPR ğŸŒ® )
          You ğŸ‘¨ğŸ¿â€ğŸŒ¾ deserve a vegan taco ğŸŒ®!

          Your effort is very much appreciated, please someone in here type '/giphy Have a taco! in a comment'
  - name: "locked: resolved âœ…"
    labeled:
      issue:
        body: |
          ğŸ· ( locked: resolved âœ… )
          This issue has been **LOCKED** because of it being resolved ğŸ‘©ğŸ½â€ğŸŒ¾!

          The issue has been fixed and is therefore considered resolved.
          If you still encounter this or it has changed, open a new issue instead of responding to solved ones.
        action: close
        locking: lock
        lock_reason: resolved
  - name: "locked: heated ğŸ§¯"
    labeled:
      issue:
        body: |
          ğŸ· ( locked: heated ğŸ§¯ )
          This issue has been **LOCKED** because of heated conversation ğŸ§¯!

          We appreciate exciting conversations, as long as they won't become too aggressive and/or emotional.
        locking: lock
        lock_reason: too heated
      pr:
        body: |
          ğŸ· ( locked: heated ğŸ§¯ )
          This pull-request has been **LOCKED** because of heated conversation ğŸ§¯!

          We appreciate exciting conversations, as long as they won't become too aggressive and/or emotional.
        locking: lock
        lock_reason: too heated
    unlabeled:
      issue:
        body: |
          Unlabeled -> ğŸ· ( locked: heated ğŸ§¯ )
          This issue has been unlocked now ğŸ–.
        locking: unlock
      pr:
        body: |
          Unlabeled -> ğŸ· ( locked: heated ğŸ§¯ )
          This pull-request has been unlocked now ğŸ–.
        locking: unlock
  - name: "locked: spam ğŸ‘®ğŸ»â€â™‚ï¸"
    labeled:
      issue:
        body: |
          ğŸ· ( locked: spam ğŸ‘®ğŸ»â€â™‚ï¸ )
          This issue has been **LOCKED** because of spam ğŸ™Š!

          Please do not spam messages and/or issues on the issue tracker. You may get blocked from this repository for doing so.
        action: close
        locking: lock
        lock_reason: spam
      pr:
        body: |
          ğŸ· ( locked: spam ğŸ‘®ğŸ»â€â™‚ï¸ )
          This pull-request has been **LOCKED** because of spam ğŸ™Š!

          Please do not spam messages and/or pull-requests on this project. You may get blocked from this repository for doing so.
        action: close
        locking: lock
        lock_reason: spam
  - name: proposal âœ¨
    labeled:
      issue:
        body: |
          ğŸ· ( proposal âœ¨ )
          Thank you @{{ issue.user.login }} for suggesting this ğŸ„.

          We really appreciate your time and help ğŸ«¶ğŸ¾.
  - name: "locked: breaking ğŸ’¥"
    labeled:
      issue:
        body: |
          ğŸ· ( locked: breaking ğŸ’¥ )
          This issue has been **LOCKED** because of breaking changes ğŸ’©!

          We appreciate exciting contributions, as long as they don't break anything.
        locking: lock
        lock_reason: breaking changes
      pr:
        body: |
          ğŸ· ( locked: breaking ğŸ’¥ )
          This pull-request has been **LOCKED** because of breaking changes ğŸ’©!

          We appreciate exciting contributions, as long as they don't break anything.
        locking: lock
        lock_reason: breaking changes
    unlabeled:
      issue:
        body: |
          Unlabeled -> ğŸ· ( locked: breaking ğŸ’¥ )
          This issue has been unlocked now ğŸ–.
        locking: unlock
      pr:
        body: |
          Unlabeled -> ğŸ· ( locked: breaking ğŸ’¥ )
          This pull-request has been unlocked now ğŸ–.
        locking: unlock
  - name: duplicate ğŸ‘¯â€â™‚ï¸
    labeled:
      issue:
        body: |
          ğŸ· ( duplicate ğŸ‘¯â€â™‚ï¸ )
          We really appreciate your time and help, but this issue already exists ğŸ«.
        action: close
  - name: good first issue ğŸ‘‘
    labeled:
      issue:
        body: |
          ğŸ· ( good first issue ğŸ‘‘ )
          This issue is easy for contributing. Everyone can work on this ğŸ„ ğŸ– ğŸ¦ƒ.

  - name: "help wanted ğŸ™ğŸ¾"
    labeled:
      issue:
        body: |
          ğŸ· ( help wanted ğŸ™ğŸ¾ )
          Hello, anybody out there ğŸ‘€ ?

          Any help would be very much appreciated ğŸ§. Maybe a '/giphy help!' on the comments could do something ğŸ¦©.
      pr:
        body: |
          ğŸ· ( help wanted ğŸ™ğŸ¾ )
          Hello, anybody out there ğŸ‘€ ?

          Any help would be very much appreciated ğŸ§. Maybe a '/giphy help!' on the comments could do something ğŸ¦©.
  - name: invalid ğŸ™Š
    labeled:
      issue:
        body: |
          ğŸ· ( invalid ğŸ™Š )
          Please follow the issue templates ğŸˆ.
        action: close
      pr:
        body: |
          ğŸ· ( invalid ğŸ™Š )
          Thank you @{{ pull_request.user.login }} for suggesting this. Please follow the pull request templates ğŸˆ.
        action: close
    unlabeled:
      issue:
        body: |
          Unlabeled -> ğŸ· ( invalid ğŸ™Š )
          Thank you for following the template. The repository owner will reply ğŸ¦¬.
        action: open
  - name: wontfix ğŸ§Œ
    labeled:
      issue:
        body: |
          ğŸ· ( wontfix ğŸ§Œ )
          This will not be worked on but we appreciate your contribution ğŸ¦™.
        action: close
    unlabeled:
      issue:
        body: |
          ğŸ· ( wontfix ğŸ§Œ )
          This has become active again ğŸ–.
        action: open
  - name: "type: hotfix ğŸš‘"
    labeled:
      issue:
        body: |
          ğŸ· ( type: hotfix ğŸš‘ )
          Whe need ğŸ‘¨ğŸ¿â€ğŸŒ¾ help, now!

          But please someone put a '/giphy everything is fine' in the comments
      pr:
        body: |
          ğŸ· ( type: hotfix ğŸš‘ )
          To the rescue ğŸ‘¨ğŸ¿â€ğŸŒ¾ !

          But please someone put a '/giphy we are just fine' in the comments
